(function(){
'use strict';
var states=['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Delhi','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Odisha','Punjab','Rajasthan','Tamil Nadu','Telangana','Uttar Pradesh','Uttarakhand','West Bengal'];
var key='cos-crm-v1'; var current=null; var charts={}; var deferredInstall=null; var DEFAULT_TERMS='Payment due within 15 days. Goods once sold will not be taken back unless agreed in writing.';
var $=function(s){return document.querySelector(s)}; var $$=function(s){return Array.from(document.querySelectorAll(s))};
var money=function(n){return 'Rs '+(Number(n)||0).toLocaleString('en-IN',{maximumFractionDigits:2})};
var id=function(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)};
var today=function(){var d=new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16)};
var db=function(){return JSON.parse(localStorage.getItem(key)||'{"users":[],"active":null}')};
var save=function(data){localStorage.setItem(key,JSON.stringify(data))};
var data=function(){var d=db(); current=d.active; return d};
var me=function(){var d=data(); return d.users.find(function(u){return u.email===d.active})};
var store=function(u){var d=db(); var i=d.users.findIndex(function(x){return x.email===u.email}); if(i>=0)d.users[i]=u; else d.users.push(u); d.active=u.email; save(d); current=u.email};
var blankUser=function(name,email,phone,pass){return {name:name,email:email,phone:phone,password:pass,role:'Admin',theme:'light',accent:'#6f3ff5',terms:DEFAULT_TERMS,seller:{name:'Cos Retail Pvt Ltd',gstin:'29ABCDE1234F1Z5',state:'Karnataka',email:email,phone:phone,address:'Business address, city, India',logo:'',signature:''},companies:[],contacts:[],leads:[],products:[],quotes:[],invoices:[],activity:[]}};
function seed(u){u.companies.push({id:id(),name:'Acme Retail Stores',industry:'Retail',gstin:'29AAACA0000A1Z5',state:'Karnataka',email:'buyer@acme.test',phone:'9876543210',address:'MG Road, Bengaluru'});u.contacts.push({id:id(),name:'Ravi Kumar',company:u.companies[0].id,email:'ravi@acme.test',phone:'9876543210',role:'Purchase Manager',status:'Customer',notes:'Prefers monthly offers'});u.products.push({id:id(),name:'Premium CRM Setup',sku:'CRM-SETUP',price:45000,tax:18,description:'Implementation, configuration and onboarding'});u.products.push({id:id(),name:'Retail Support Plan',sku:'SUP-RET',price:12000,tax:18,description:'Monthly business support'});u.leads=[{id:id(),name:'North Zone Distributor',value:85000,stage:'New'},{id:id(),name:'Corporate Admin Team',value:125000,stage:'Qualified'}];return u}
function init(){if(!navigator.onLine)$('#offlineLock').classList.add('show'); window.addEventListener('offline',function(){$('#offlineLock').classList.add('show')}); window.addEventListener('online',function(){$('#offlineLock').classList.remove('show')}); if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(function(){}); window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredInstall=e}); initLandingTheme(); bindAuth(); bindPreviewModal(); var u=me(); if(u)showApp(u); else showLanding();}
function bindAuth(){$$('[data-landing="signup"]').forEach(function(b){b.onclick=quickSignup}); var file=$('#landingImportFile'); $$('[data-landing="import"]').forEach(function(b){b.onclick=function(){file&&file.click()}}); if(file)file.onchange=landingImport; if($('#landingTheme'))$('#landingTheme').onclick=toggleLandingTheme}
function initLandingTheme(){var t=localStorage.getItem('cos-crm-landing-theme'); document.body.classList.toggle('dark',t==='dark'); updateLandingThemeBtn()}
function updateLandingThemeBtn(){var b=$('#landingTheme'); if(b)b.textContent=document.body.classList.contains('dark')?'Light':'Dark'}
function toggleLandingTheme(){document.body.classList.toggle('dark'); localStorage.setItem('cos-crm-landing-theme',document.body.classList.contains('dark')?'dark':'light'); updateLandingThemeBtn()}
function quickSignup(){var email='user-'+id()+'@local'; var u=seed(blankUser('Admin',email,'',Math.random().toString(36).slice(2,10))); store(u); showApp(u)}
function landingImport(e){var f=e.target.files[0]; e.target.value=''; if(!f)return; if(!window.XLSX)return toast('Excel library still loading'); var r=new FileReader(); r.onload=function(){var wb=XLSX.read(r.result,{type:'array'}); var email='user-'+id()+'@local'; var u=blankUser('Admin',email,'',Math.random().toString(36).slice(2,10)); wb.SheetNames.forEach(function(n){var low=n.toLowerCase(); if(u[low]!==undefined)u[low]=XLSX.utils.sheet_to_json(wb.Sheets[n]).map(unflat)}); store(u); showApp(u); toast('Account restored from Excel')}; r.readAsArrayBuffer(f)}
function showLanding(){$('#landing').classList.remove('hidden');$('#app').classList.add('hidden')}
function showApp(u){$('#landing').classList.add('hidden');$('#app').classList.remove('hidden'); document.body.classList.toggle('dark',u.theme==='dark'); applyAccent(u.accent); renderShell()}
function applyAccent(c){var hex=parseColor(c)||'#6f3ff5'; document.documentElement.style.setProperty('--accent',hex); var m=document.querySelector('meta[name="theme-color"]'); if(m)m.content=hex}
function parseColor(v){if(!v)return null; v=String(v).trim(); if(/^#[0-9a-f]{6}$/i.test(v))return v; if(/^[0-9a-f]{8}$/i.test(v))return '#'+v.slice(2); if(/^[0-9a-f]{6}$/i.test(v))return '#'+v; return null}
function renderShell(){var u=me(); $('#profile').textContent=u.name+' | '+u.role; $('#theme').textContent=u.theme==='dark'?'Light':'Dark'; $('#logout').onclick=function(){var d=db();d.active=null;save(d);showLanding()}; $('#theme').onclick=function(){u.theme=u.theme==='dark'?'light':'dark';store(u);showApp(u)}; $('#install').onclick=function(){if(deferredInstall)deferredInstall.prompt(); else toast('Use browser install option')}; $$('.nav').forEach(function(b){b.onclick=function(){go(b.dataset.page)}}); renderPages(); go('dashboard')}
function page(title,html){return '<section class="content page" data-name="'+title.toLowerCase()+'">'+html+'</section>'}
function renderPages(){var pages=$('#pages'); pages.innerHTML=page('dashboard','<div class="kpis"><div class="kpi"><span>Revenue</span><b id="kRevenue"></b></div><div class="kpi"><span>Quotes</span><b id="kQuotes"></b></div><div class="kpi"><span>Contacts</span><b id="kContacts"></b></div></div><div class="two" style="margin-top:18px"><div class="panel"><div class="panel-head"><h3>Revenue snapshot</h3></div><div class="chart-box"><canvas id="pipelineChart"></canvas></div></div><div class="panel"><div class="panel-head"><h3>Recent activity</h3></div><div id="activity"></div></div></div>')+crudPage('companies','Company profile',['name','industry','gstin','state','email','phone','address'])+crudPage('contacts','Contact storage',['name','company','email','phone','gstin','address','role','status','notes'])+leadsPage()+crudPage('products','Product catalogue',['name','sku','price','tax','stock','description'],stockPanel())+docPage('quotes','Quotation')+docPage('invoices','Invoice')+documentsPage()+marketingPage()+page('analytics','<div class="kpis"><div class="kpi"><span>Total sales</span><b id="aSales"></b></div><div class="kpi"><span>Tax collected</span><b id="aTax"></b></div><div class="kpi"><span>Discounts</span><b id="aDiscount"></b></div><div class="kpi"><span>Average invoice</span><b id="aAvg"></b></div></div><div class="two" style="margin-top:18px"><div class="panel"><div class="panel-head"><h3>Revenue by document</h3></div><div class="chart-box"><canvas id="revenueChart"></canvas></div></div><div class="panel"><div class="panel-head"><h3>Lead stages</h3></div><div class="chart-box"><canvas id="stageChart"></canvas></div></div></div>')+settingsPage(); bindAll(); renderAll()}
function stockPanel(){return '<div class="panel" style="margin-top:18px"><div class="panel-head"><h3>Product stock list</h3></div><div class="table-wrap"><table><thead><tr><th>Product</th><th>SKU</th><th>Price</th><th>Stock on hand</th></tr></thead><tbody id="stockTable"></tbody></table></div></div>'}
function renderStock(){var u=me(); var tb=$('#stockTable'); if(!tb)return; tb.innerHTML=u.products.map(function(p){return '<tr><td><b>'+esc(p.name)+'</b></td><td>'+esc(p.sku||'')+'</td><td>'+money(p.price)+'</td><td>'+(Number(p.stock)||0)+'</td></tr>'}).join('')||'<tr><td colspan="4">No products yet</td></tr>'}
function inputFor(name,prefix){if(name==='state'||name==='status'||name==='stage'||name==='company')return '<label>'+cap(name)+'<select id="'+prefix+name+'"></select></label>'; if(name==='address'||name==='notes'||name==='description')return '<label class="wide">'+cap(name)+'<textarea id="'+prefix+name+'"></textarea></label>'; if(name==='gstin')return '<label>GSTIN (optional)<input id="'+prefix+name+'" type="text" placeholder="15-digit GSTIN"></label>'; var type=(name==='email'?'email':(name==='phone'?'tel':(name==='value'||name==='price'||name==='tax'||name==='stock'?'number':(name==='close'?'date':'text')))); return '<label>'+cap(name)+'<input id="'+prefix+name+'" type="'+type+'"></label>'}
function crudPage(name,title,fields,extra){var p=name+'_'; return page(name,'<div class="two"><form class="panel form" id="'+name+'Form"><h3 class="wide">'+title+'</h3><input type="hidden" id="'+p+'id">'+fields.map(function(f){return inputFor(f,p)}).join('')+'<button class="btn primary">Save</button></form><div class="panel"><div class="panel-head"><h3>'+cap(name)+'</h3><button class="btn ghost" data-export="'+name+'">Export XLSX</button></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Detail</th><th>Status</th><th></th></tr></thead><tbody id="'+name+'Table"></tbody></table></div></div></div>'+(extra||''))}
function leadsPage(){return page('leads','<div class="panel"><div class="panel-head"><h3>Lead management</h3></div><div class="lead-entry"><label>Lead name<input id="leadName" placeholder="Lead name"></label><label>Value<input id="leadValue" type="number" placeholder="Value"></label><button id="addLead" class="btn primary">Add lead</button></div><div id="leadBoard" class="kanban"></div></div>')}
function docPage(name,label){var p=name+'_';return page(name,'<div class="doc-grid"><form class="panel" id="'+name+'Form"><div class="panel-head"><h3>'+label+' builder</h3><button type="button" class="btn ghost" data-newdoc="'+name+'">New</button></div><input type="hidden" id="'+p+'id"><div class="form two"><label>'+label+' number<input id="'+p+'number" required></label><label>Date & time<input id="'+p+'date" type="datetime-local"></label><label>Bill To (company or contact)<select id="'+p+'company"></select></label><label>Place of supply<select id="'+p+'state"></select></label></div><datalist id="'+name+'_productList"></datalist><div id="'+name+'Items"></div><div id="'+name+'Descs"></div><div class="actions" style="margin:16px 0;justify-content:space-between;align-items:flex-end"><label style="margin:0">Discount amount<input id="'+p+'discount" type="number" value="0"></label><button type="button" class="btn ghost" data-additem="'+name+'">Add item</button></div><div class="form"><label class="wide">Terms & Conditions<textarea id="'+p+'terms"></textarea></label></div><div id="'+name+'Totals" class="totals"></div><div class="actions" style="margin-top:16px"><button class="btn primary">Save '+label.toLowerCase()+'</button><button type="button" class="btn ghost" data-preview="'+name+'">Preview</button><button type="button" class="btn ghost" data-print="'+name+'">Print</button><button type="button" class="btn ghost" data-export="'+name+'">Export XLSX</button></div></form><div class="panel"><div class="panel-head"><h3>Saved '+label.toLowerCase()+'s</h3></div><div class="table-wrap"><table><thead><tr><th>No.</th><th>Company</th><th>Total</th><th></th></tr></thead><tbody id="'+name+'Table"></tbody></table></div></div></div>')}
function documentsPage(){return page('documents','<div class="panel"><div class="panel-head"><h3>All quotations & invoices</h3><div class="actions"><label style="margin:0;font-weight:700">Filter <select id="docsFilter" style="width:auto;display:inline-block"><option value="all">All</option><option value="quotes">Quotations only</option><option value="invoices">Invoices only</option></select></label></div></div><div class="table-wrap"><table><thead><tr><th>Type</th><th>No.</th><th>Company</th><th>Date</th><th>Total</th><th></th></tr></thead><tbody id="documentsTable"></tbody></table></div></div>')}
function renderDocumentsList(){var u=me(); var tb=$('#documentsTable'); if(!tb)return; var filt=$('#docsFilter'); var mode=filt?filt.value:'all'; var rows=[]; if(mode!=='invoices')rows=rows.concat(u.quotes.map(function(o){return {type:'quotes',label:'Quotation',o:o}})); if(mode!=='quotes')rows=rows.concat(u.invoices.map(function(o){return {type:'invoices',label:'Invoice',o:o}})); rows.sort(function(a,b){return new Date(b.o.date)-new Date(a.o.date)}); tb.innerHTML=rows.map(function(r){var o=r.o; return '<tr><td><span class="chip">'+r.label+'</span></td><td><b>'+esc(o.number)+'</b></td><td>'+esc(companyName(o.company))+'</td><td>'+(o.date?new Date(o.date).toLocaleDateString():'')+'</td><td>'+money(o.totals&&o.totals.total)+'</td><td><div class="actions"><button class="btn ghost small" onclick="Cos.preview(\''+r.type+'\',\''+o.id+'\')">Preview</button><button class="btn ghost small" onclick="Cos.editDoc(\''+r.type+'\',\''+o.id+'\')">Edit</button><button class="btn danger small" onclick="Cos.del(\''+r.type+'\',\''+o.id+'\')">Delete</button></div></td></tr>'}).join('')||'<tr><td colspan="6">No documents yet</td></tr>'}
function marketingPage(){return page('marketing','<div class="panel"><div class="panel-head"><h3>Email campaign</h3></div><div class="form two"><label class="wide">Subject<input id="subject" value="Business offer from Cos CRM"></label><label class="wide">Message<textarea id="message">Hello, we are sharing our latest business offer with you.</textarea></label></div><div class="panel-head" style="margin-top:14px"><h3>Recipients</h3><label style="font-weight:700"><input type="checkbox" id="selectAllContacts"> Select all</label></div><div class="table-wrap"><table><thead><tr><th></th><th>Name</th><th>Email</th><th>Status</th></tr></thead><tbody id="marketingContacts"></tbody></table></div><div class="actions" style="margin-top:16px"><button type="button" id="sendCampaign" class="btn primary">Send via Email app</button></div></div>')}
function settingsPage(){return page('settings','<div class="two"><form id="settingsForm" class="panel form"><h3 class="wide">Seller and theme</h3><label>Business name<input id="seller_name"></label><label>GSTIN<input id="seller_gstin"></label><label>State<select id="seller_state"></select></label><label>Email<input id="seller_email"></label><label>Phone<input id="seller_phone"></label><label class="wide">Address<textarea id="seller_address"></textarea></label><label>Logo upload<input id="seller_logo" type="file" accept="image/*"><div class="img-row"><img id="logoPreview" class="img-preview hidden" alt="Logo preview"><button type="button" id="removeLogo" class="btn ghost small hidden">Remove</button></div></label><label>Signature upload<input id="seller_signature" type="file" accept="image/*"><div class="img-row"><img id="signaturePreview" class="img-preview hidden" alt="Signature preview"><button type="button" id="removeSignature" class="btn ghost small hidden">Remove</button></div></label><label>App/PDF colour ARGB or hex<div class="color-row"><input id="accent" placeholder="#6f3ff5 or AARRGGBB"><input id="accentSwatch" type="color"></div></label><label class="wide">Default Terms & Conditions<textarea id="settings_terms"></textarea></label><button class="btn primary">Save settings</button></form><div class="panel"><div class="panel-head"><h3>Data and account</h3></div><div class="stack"><div class="btn-row"><button id="exportAll" class="btn ghost small">Export full XLSX backup</button><label class="file-btn small">Import existing Excel<input id="importExcel" type="file" accept=".xlsx,.xls"></label></div><button id="deleteAccount" class="btn danger">Delete account</button></div><p class="muted">Frontend role access is included. Data is stored in this browser and can be backed up as Excel for server upload.</p></div></div>')}
function bindAll(){['companies','contacts','products'].forEach(bindCrud); ['quotes','invoices'].forEach(bindDoc); $('#addLead').onclick=addLead; $('#selectAllContacts').onchange=function(){var c=this.checked; $$('.campaignPick').forEach(function(x){x.checked=c})}; $('#sendCampaign').onclick=sendCampaign; $('#settingsForm').onsubmit=saveSettings; $('#accentSwatch').oninput=function(){$('#accent').value=this.value}; $('#seller_logo').onchange=function(e){previewFile(e.target.files[0],'logoPreview')}; $('#seller_signature').onchange=function(e){previewFile(e.target.files[0],'signaturePreview')}; $('#removeLogo').onclick=function(){clearSellerImage('logo','logoPreview','seller_logo')}; $('#removeSignature').onclick=function(){clearSellerImage('signature','signaturePreview','seller_signature')}; $('#exportAll').onclick=exportAll; $('#deleteAccount').onclick=deleteAccount; $('#importExcel').onchange=importExcel; var df=$('#docsFilter'); if(df)df.onchange=renderDocumentsList; $$('.btn[data-export]').forEach(function(b){b.onclick=function(){exportSheet(b.dataset.export)}})}
function go(name){$$('.nav').forEach(function(b){b.classList.toggle('active',b.dataset.page===name)}); $$('.page').forEach(function(p){p.classList.toggle('hidden',p.dataset.name!==name)}); $('#title').textContent=cap(name); renderAll()}
function renderAll(){var u=me(); if(!u)return; fillSelects(); renderDashboard(); ['companies','contacts','products'].forEach(renderCrud); renderStock(); renderLeads(); ['quotes','invoices'].forEach(renderDocs); renderDocumentsList(); renderCampaign(); renderAnalytics(); renderSettings()}
function fillSelects(){var u=me(); $$('select').forEach(function(s){if(s.id.endsWith('state')||s.id.includes('_state'))s.innerHTML=states.map(function(x){return '<option>'+x+'</option>'}).join('')}); var cc=$('#contacts_company'); if(cc)cc.innerHTML='<option value="">Select</option>'+u.companies.map(function(c){return '<option value="'+c.id+'">'+esc(c.name)+'</option>'}).join(''); ['quotes_company','invoices_company'].forEach(function(idn){var s=$('#'+idn); if(!s)return; var coOpts=u.companies.map(function(c){return '<option value="co:'+c.id+'">'+esc(c.name)+'</option>'}).join(''); var ctOpts=u.contacts.map(function(ct){return '<option value="ct:'+ct.id+'">'+esc(ct.name)+'</option>'}).join(''); s.innerHTML='<option value="">Select</option>'+(coOpts?'<optgroup label="Companies">'+coOpts+'</optgroup>':'')+(ctOpts?'<optgroup label="Contacts">'+ctOpts+'</optgroup>':'')}); var st=$('#contacts_status'); if(st)st.innerHTML='<option>Customer</option><option>Prospect</option><option>Vendor</option><option>Partner</option>'; ['quotes_productList','invoices_productList'].forEach(function(idn){var dl=$('#'+idn); if(dl)dl.innerHTML=u.products.map(function(p){return '<option value="'+esc(p.name)+'" label="Stock '+(Number(p.stock)||0)+' | Rs '+p.price+'"></option>'}).join('')})}
function bindCrud(name){var form=$('#'+name+'Form'); if(!form)return; form.onsubmit=function(e){e.preventDefault(); var u=me(); var p=name+'_'; var obj={id:$('#'+p+'id').value||id()}; Array.from(form.querySelectorAll('input,select,textarea')).forEach(function(el){var k=el.id.replace(p,''); if(k&&k!=='id')obj[k]=el.value}); upsert(u[name],obj); log(u,'Saved '+cap(name)+' '+(obj.name||'')); store(u); form.reset(); $('#'+p+'id').value=''; renderAll()}}
function renderCrud(name){var u=me(); var tb=$('#'+name+'Table'); if(!tb)return; tb.innerHTML=u[name].map(function(o){return '<tr><td><b>'+esc(o.name||o.sku)+'</b></td><td>'+esc(o.email||o.company||o.industry||o.sku||money(o.value||o.price))+'</td><td>'+esc(o.status||o.stage||o.gstin||((o.tax||'')+'%'))+'</td><td><div class="actions"><button class="btn ghost small" onclick="Cos.edit(\''+name+'\',\''+o.id+'\')">Edit</button><button class="btn danger small" onclick="Cos.del(\''+name+'\',\''+o.id+'\')">Delete</button></div></td></tr>'}).join('')||'<tr><td colspan="4">No records yet</td></tr>'}
function addLead(){var u=me(); var name=($('#leadName')&&$('#leadName').value.trim())||'New lead'; var value=Number($('#leadValue')&&$('#leadValue').value)||0; u.leads.push({id:id(),name:name,value:value,stage:'New'}); if($('#leadName'))$('#leadName').value=''; if($('#leadValue'))$('#leadValue').value=''; store(u); renderAll()}
function renderLeads(){var u=me(); var el=$('#leadBoard'); if(!el)return; var stages=['New','Qualified','Proposal','Won']; el.innerHTML=stages.map(function(s){return '<div class="lane"><b>'+s+'</b>'+u.leads.filter(function(l){return l.stage===s}).map(function(l){return '<div class="card"><b>'+esc(l.name)+'</b><p>'+money(l.value)+'</p><div class="actions"><button class="btn ghost small" onclick="Cos.moveLead(\''+l.id+'\')">Next</button><button class="btn danger small" onclick="Cos.deleteLead(\''+l.id+'\')">Delete</button></div></div>'}).join('')+'</div>'}).join('')}
function bindDoc(name){var form=$('#'+name+'Form'); if(!form)return; form.onsubmit=function(e){e.preventDefault(); saveDoc(name)}; $$('[data-additem="'+name+'"]').forEach(function(b){b.onclick=function(){addItem(name)}}); $$('[data-newdoc="'+name+'"]').forEach(function(b){b.onclick=function(){newDoc(name)}}); $$('[data-preview="'+name+'"]').forEach(function(b){b.onclick=function(){previewDoc(name,getDoc(name))}}); $$('[data-pdf="'+name+'"]').forEach(function(b){b.onclick=function(){pdfDoc(name)}}); $$('[data-print="'+name+'"]').forEach(function(b){b.onclick=function(){printDoc(name)}}); newDoc(name)}
function newDoc(name){var p=name+'_'; var f=$('#'+name+'Form'); if(!f)return; f.reset(); $('#'+p+'id').value=''; var seq=String(((me()[name]||[]).length||0)+1).padStart(4,'0'); $('#'+p+'number').value=(name==='quotes'?'QT-':'INV-')+seq; $('#'+p+'date').value=today(); $('#'+p+'terms').value=me().terms||DEFAULT_TERMS; $('#'+name+'Items').innerHTML=''; $('#'+name+'Descs').innerHTML=''; addItem(name); calcDoc(name)}
function addItem(name,item){var wrap=$('#'+name+'Items'); var group=document.createElement('div'); group.className='item-group'; var desc=item&&item.desc?item.desc:null; group.innerHTML='<div class="line-item"><label>Product or service<input list="'+name+'_productList" value="'+esc(item&&item.name||'')+'"></label><label>Qty<input type="number" value="'+(item&&item.qty||1)+'"></label><label>Rate<input type="number" value="'+(item&&item.rate||0)+'"></label><label>GST %<input type="number" value="'+(item&&item.tax||18)+'"></label><button type="button" class="btn danger small">x</button></div><div class="desc-item"><label>Description<textarea placeholder="Manual description for this item">'+esc(desc&&desc.body||'')+'</textarea></label><button type="button" class="btn ghost small" data-clear-desc>Clear</button></div>'; group.querySelector('.line-item button').onclick=function(){group.remove();calcDoc(name)}; group.querySelector('[data-clear-desc]').onclick=function(){group.querySelector('.desc-item textarea').value=''}; var rowInputs=group.querySelectorAll('.line-item input'); rowInputs[0].addEventListener('input',function(){var p=(me().products||[]).find(function(x){return x.name===rowInputs[0].value}); if(p){rowInputs[2].value=p.price; rowInputs[3].value=p.tax; calcDoc(name)}}); group.oninput=function(){calcDoc(name)}; wrap.appendChild(group)}
function getDoc(name){var p=name+'_'; var items=$$('#'+name+'Items .item-group').map(function(g){var row=g.querySelector('.line-item'); var a=row.querySelectorAll('input'); var d=g.querySelector('.desc-item'); return {name:a[0].value,qty:Number(a[1].value)||0,rate:Number(a[2].value)||0,tax:Number(a[3].value)||0,desc:{title:'Description',body:d.querySelector('textarea').value}}}); var descs=items.map(function(i){return i.desc}); var obj={id:$('#'+p+'id').value||id(),number:$('#'+p+'number').value,date:$('#'+p+'date').value,company:$('#'+p+'company').value,state:$('#'+p+'state').value,color:me().accent,discount:Number($('#'+p+'discount').value)||0,terms:$('#'+p+'terms').value,items:items,descs:descs}; obj.totals=totals(obj); return obj}
function totals(doc){var sub=0,tax=0; doc.items.forEach(function(i){var line=i.qty*i.rate; sub+=line; tax+=line*i.tax/100}); var total=Math.max(0,sub+tax-(doc.discount||0)); return {sub:sub,tax:tax,discount:doc.discount||0,total:total}}
function calcDoc(name){var box=$('#'+name+'Totals'); if(!box)return; var t=totals({items:$$('#'+name+'Items .line-item').map(function(r){var a=r.querySelectorAll('input');return{qty:Number(a[1].value)||0,rate:Number(a[2].value)||0,tax:Number(a[3].value)||0}}),discount:Number($('#'+name+'_discount').value)||0}); box.innerHTML='<div><span>Subtotal</span><b>'+money(t.sub)+'</b></div><div><span>GST</span><b>'+money(t.tax)+'</b></div><div><span>Discount</span><b>'+money(t.discount)+'</b></div><div><span>Total</span><b>'+money(t.total)+'</b></div>'}
function adjustStock(u,items,sign){(items||[]).forEach(function(i){var p=u.products.find(function(x){return x.name===i.name}); if(p)p.stock=(Number(p.stock)||0)+sign*(Number(i.qty)||0)})}
function saveDoc(name){var u=me(); var old=u[name].find(function(x){return x.id===$('#'+name+'_id').value}); if(old)adjustStock(u,old.items,1); var obj=getDoc(name); if(name==='quotes'||name==='invoices')adjustStock(u,obj.items,-1); upsert(u[name],obj); log(u,'Saved '+(name==='quotes'?'quotation ':'invoice ')+obj.number); store(u); renderAll(); newDoc(name); toast('Saved. Next '+(name==='quotes'?'quotation':'invoice')+' number ready')}
function renderDocs(name){var u=me(); var tb=$('#'+name+'Table'); if(!tb)return; tb.innerHTML=u[name].map(function(o){return '<tr><td><b>'+esc(o.number)+'</b></td><td>'+esc(companyName(o.company))+'</td><td>'+money(o.totals&&o.totals.total)+'</td><td><div class="actions"><button class="btn ghost small" onclick="Cos.editDoc(\''+name+'\',\''+o.id+'\')">Edit</button><button class="btn ghost small" onclick="Cos.preview(\''+name+'\',\''+o.id+'\')">Preview</button><button class="btn danger small" onclick="Cos.del(\''+name+'\',\''+o.id+'\')">Delete</button></div></td></tr>'}).join('')||'<tr><td colspan="4">No documents yet</td></tr>'}
function buildPdf(name,doc){var u=me(), seller=u.seller, c=billTo(doc.company); var color=parseColor(doc.color)||u.accent; var inter=seller.state&&doc.state&&seller.state!==doc.state; var gstLabel=inter?'IGST':'CGST / SGST'; var rows=doc.items.map(function(i,n){var line=i.qty*i.rate; var d=i.desc||(doc.descs&&doc.descs[n])||{}; var descRow=(d.title||d.body)?'<tr class="pdf-desc-row"><td></td><td colspan="5"><b>'+esc(d.title||'Description')+'</b><br>'+esc(d.body||'')+'</td></tr>':'';return '<tr><td>'+(n+1)+'</td><td><b>'+esc(i.name)+'</b></td><td>'+i.qty+'</td><td>'+money(i.rate)+'</td><td>'+i.tax+'%</td><td>'+money(line)+'</td></tr>'+descRow}).join(''); var logo=seller.logo?'<img class="pdf-logo" src="'+seller.logo+'">':'<div class="brand"><img src="logo.svg" alt="Cos CRM" class="brand-mark" width="38" height="38" style="width:38px;height:38px;object-fit:contain;flex:none">Cos CRM</div>'; var sig=seller.signature?'<img src="'+seller.signature+'">':''; var billGst=c.gstin?'<br>GSTIN: '+esc(c.gstin):''; return '<div class="pdf-doc" style="--pdf:'+color+'"><div class="pdf-bar"></div><div class="pdf-head"><div>'+logo+'<h3>'+esc(seller.name)+'</h3><p>'+esc(seller.address)+'<br>'+esc(seller.email)+' | '+esc(seller.phone)+'<br>GSTIN: '+esc(seller.gstin)+'</p></div><div class="pdf-title"><h1>'+(name==='quotes'?'QUOTATION':'INVOICE')+'</h1><div class="pdf-meta">No: '+esc(doc.number)+'<br>Date: '+new Date(doc.date).toLocaleString()+'</div></div></div><div class="pdf-boxes"><div class="pdf-box"><b>Bill To</b><p>'+esc(c.name)+'<br>'+esc(c.address)+'<br>'+esc(c.email)+' | '+esc(c.phone)+billGst+'</p></div><div class="pdf-box"><b>Supply & Tax</b><p>Seller state: '+esc(seller.state)+'<br>Place of supply: '+esc(doc.state)+'<br>Tax type: '+gstLabel+'</p></div></div><table><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>Rate</th><th>GST</th><th>Amount</th></tr></thead><tbody>'+rows+'</tbody></table><div class="pdf-total"><div><span>Subtotal</span><b>'+money(doc.totals.sub)+'</b></div><div><span>'+gstLabel+'</span><b>'+money(doc.totals.tax)+'</b></div><div><span>Discount</span><b>'+money(doc.totals.discount)+'</b></div><div><span>Grand Total</span><strong>'+money(doc.totals.total)+'</strong></div></div><h4>Terms & Conditions</h4><p>'+esc(doc.terms)+'</p><div class="pdf-sign"><div><b>Thank you for your business.</b></div><div>'+sig+'<br><b>Authorized Signature</b></div></div></div>'}
function pdfDoc(name){var doc=getDoc(name); downloadPdf(name,doc)}
function downloadPdf(name,doc){var stage=$('#pdfStage'); stage.innerHTML=buildPdf(name,doc); if(window.html2pdf){html2pdf().set({margin:0,filename:doc.number+'.pdf',html2canvas:{scale:2},jsPDF:{unit:'pt',format:'a4',orientation:'portrait'}}).from(stage.firstChild).save()} else printDoc(name,doc)}
function printDoc(name,doc){doc=doc||getDoc(name); var w=window.open('','print'); w.document.write('<html><head><title>'+doc.number+'</title><link rel="stylesheet" href="styles.css"></head><body>'+buildPdf(name,doc)+'</body></html>'); w.document.close(); setTimeout(function(){w.print()},400)}
var previewState=null;
function previewDoc(name,doc){previewState={name:name,doc:doc}; var body=$('#docPreviewBody'); if(body)body.innerHTML=buildPdf(name,doc); var modal=$('#docPreviewModal'); if(modal)modal.classList.remove('hidden')}
function closePreview(){var modal=$('#docPreviewModal'); if(modal)modal.classList.add('hidden'); previewState=null}
function bindPreviewModal(){var close=$('#closeDocPreview'); if(close)close.onclick=closePreview; var modal=$('#docPreviewModal'); if(modal)modal.onclick=function(e){if(e.target===modal)closePreview()}; var dl=$('#docPreviewDownload'); if(dl)dl.onclick=function(){if(previewState)downloadPdf(previewState.name,previewState.doc)}; var pr=$('#docPreviewPrint'); if(pr)pr.onclick=function(){if(previewState)printDoc(previewState.name,previewState.doc)}}
function renderDashboard(){var u=me(); $('#kRevenue').textContent=money(sum(u.invoices.map(function(x){return x.totals.total}))); $('#kQuotes').textContent=u.quotes.length; $('#kContacts').textContent=u.contacts.length; $('#activity').innerHTML=(u.activity||[]).slice(-8).reverse().map(function(a){return '<div class="card"><b>'+esc(a.text)+'</b><p class="muted">'+new Date(a.at).toLocaleString()+'</p></div>'}).join('')||'<p class="muted">No activity yet.</p>'; chart('pipelineChart','bar',['Quotes','Invoices'],[sum(u.quotes.map(function(d){return d.totals.total})),sum(u.invoices.map(function(d){return d.totals.total}))])}
function renderAnalytics(){var u=me(), inv=u.invoices; if(!$('#aSales'))return; var sales=sum(inv.map(function(x){return x.totals.total})), tax=sum(inv.map(function(x){return x.totals.tax})), dis=sum(inv.map(function(x){return x.totals.discount})); $('#aSales').textContent=money(sales); $('#aTax').textContent=money(tax); $('#aDiscount').textContent=money(dis); $('#aAvg').textContent=money(inv.length?sales/inv.length:0); chart('revenueChart','line',u.invoices.map(function(x){return x.number}),u.invoices.map(function(x){return x.totals.total})); var stages=['New','Qualified','Proposal','Won']; chart('stageChart','doughnut',stages,stages.map(function(s){return u.leads.filter(function(l){return l.stage===s}).length}))}
function chart(idn,type,labels,values){var el=$('#'+idn); if(!el||!window.Chart)return; if(charts[idn])charts[idn].destroy(); charts[idn]=new Chart(el,{type:type,data:{labels:labels,datasets:[{data:values,borderColor:me().accent,backgroundColor:['#6f3ff5','#00a6a6','#ffb020','#ef476f'],tension:.35}]},options:{maintainAspectRatio:false,plugins:{legend:{display:type==='doughnut'}},scales:type==='doughnut'?{}:{y:{beginAtZero:true}}}})}
function renderCampaign(){var u=me(); var tb=$('#marketingContacts'); if(!tb)return; tb.innerHTML=u.contacts.map(function(c){return '<tr><td><input type="checkbox" class="campaignPick" value="'+esc(c.email||'')+'"></td><td>'+esc(c.name)+'</td><td>'+esc(c.email||'')+'</td><td>'+esc(c.status||'')+'</td></tr>'}).join('')||'<tr><td colspan="4">No contacts yet</td></tr>'}
function sendCampaign(){var emails=$$('.campaignPick:checked').map(function(x){return x.value}).filter(Boolean); if(!emails.length)return toast('Select at least one contact'); var subject=encodeURIComponent($('#subject').value||''); var body=encodeURIComponent($('#message').value||''); window.location.href='mailto:?bcc='+encodeURIComponent(emails.join(','))+'&subject='+subject+'&body='+body}
function renderSettings(){var u=me(); if(!$('#seller_name'))return; Object.keys(u.seller).forEach(function(k){var el=$('#seller_'+k); if(el&&el.type!=='file')el.value=u.seller[k]||''}); $('#accent').value=u.accent; $('#accentSwatch').value=parseColor(u.accent)||'#6f3ff5'; $('#settings_terms').value=u.terms||DEFAULT_TERMS; setPreview('logoPreview',u.seller.logo); setPreview('signaturePreview',u.seller.signature)}
function setPreview(idn,src){var el=$('#'+idn); if(!el)return; var btn=$('#remove'+cap(idn.replace('Preview',''))); if(src){el.src=src;el.classList.remove('hidden'); if(btn)btn.classList.remove('hidden')} else {el.removeAttribute('src');el.classList.add('hidden'); if(btn)btn.classList.add('hidden')}}
function clearSellerImage(key,previewId,inputId){var u=me(); u.seller[key]=''; store(u); setPreview(previewId,''); if($('#'+inputId))$('#'+inputId).value=''; toast(cap(key)+' removed')}
function previewFile(file,idn){if(!file)return; var r=new FileReader(); r.onload=function(){setPreview(idn,r.result)}; r.readAsDataURL(file)}
function saveSettings(e){e.preventDefault(); var u=me(); ['name','gstin','state','email','phone','address'].forEach(function(k){u.seller[k]=$('#seller_'+k).value}); u.terms=$('#settings_terms').value||DEFAULT_TERMS; var color=parseColor($('#accent').value); if(color)u.accent=color; var logo=$('#seller_logo').files[0], sig=$('#seller_signature').files[0]; function done(){store(u); applyAccent(u.accent); renderAll(); toast('Settings saved')} if(logo||sig){readFiles([[logo,'logo'],[sig,'signature']],u.seller,done)} else done()}
function readFiles(list,target,done){var pending=list.filter(function(x){return x[0]}).length; if(!pending)return done(); list.forEach(function(pair){if(!pair[0])return; var r=new FileReader(); r.onload=function(){target[pair[1]]=r.result; if(--pending===0)done()}; r.readAsDataURL(pair[0])})}
function exportSheet(name){var u=me(); if(!window.XLSX)return toast('Excel library still loading'); var wb=XLSX.utils.book_new(); var rows=(u[name]||[]).map(flat); XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),name); XLSX.writeFile(wb,'cos-crm-'+name+'.xlsx')}
function exportAll(){var u=me(); if(!window.XLSX)return toast('Excel library still loading'); var wb=XLSX.utils.book_new(); ['companies','contacts','leads','products','quotes','invoices'].forEach(function(n){XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet((u[n]||[]).map(flat)),n)}); XLSX.writeFile(wb,'cos-crm-full-backup.xlsx')}
function importExcel(e){var f=e.target.files[0]; if(!f||!window.XLSX)return; var r=new FileReader(); r.onload=function(){var wb=XLSX.read(r.result,{type:'array'}); var u=me(); wb.SheetNames.forEach(function(n){var low=n.toLowerCase(); if(u[low])u[low]=XLSX.utils.sheet_to_json(wb.Sheets[n]).map(unflat)}); store(u); renderAll(); toast('Excel imported')}; r.readAsArrayBuffer(f)}
function deleteAccount(){if(!confirm('Delete this Cos CRM account and all local data?'))return; var d=db(); d.users=d.users.filter(function(u){return u.email!==d.active}); d.active=null; save(d); showLanding()}
function edit(name,rowid){var u=me(), o=u[name].find(function(x){return x.id===rowid}); if(!o)return; go(name); var p=name+'_'; Object.keys(o).forEach(function(k){var el=$('#'+p+k); if(el)el.value=o[k]});}
function del(name,rowid){var u=me(); if(name==='quotes'||name==='invoices'){var doc=u[name].find(function(x){return x.id===rowid}); if(doc)adjustStock(u,doc.items,1)} u[name]=u[name].filter(function(x){return x.id!==rowid}); store(u); renderAll()}
function editDoc(name,rowid){var u=me(), o=u[name].find(function(x){return x.id===rowid}); if(!o)return; go(name); var p=name+'_'; ['id','number','date','company','state','discount','terms'].forEach(function(k){var el=$('#'+p+k); if(el)el.value=o[k]||''}); var cel=$('#'+p+'company'); if(cel&&cel.value&&cel.value.indexOf(':')<0)cel.value='co:'+cel.value; $('#'+name+'Items').innerHTML=''; $('#'+name+'Descs').innerHTML=''; (o.items||[]).forEach(function(i,n){if(!i.desc&&o.descs&&o.descs[n])i.desc=o.descs[n]; addItem(name,i)}); calcDoc(name)}
function cap(s){return String(s).replace(/^./,function(c){return c.toUpperCase()})} function esc(s){return String(s==null?'':s).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})} function sum(a){return a.reduce(function(t,n){return t+(Number(n)||0)},0)} function upsert(a,o){var i=a.findIndex(function(x){return x.id===o.id}); if(i>=0)a[i]=o; else a.push(o)} function billTo(val){var u=me(); if(!val)return {}; if(val.indexOf('ct:')===0){var ct=u.contacts.find(function(x){return x.id===val.slice(3)}); if(!ct)return{}; var co=ct.company?u.companies.find(function(x){return x.id===ct.company}):null; return {name:ct.name,address:ct.address||(co&&co.address)||'',email:ct.email||'',phone:ct.phone||'',gstin:ct.gstin||(co&&co.gstin)||''}} var cid=val.indexOf('co:')===0?val.slice(3):val; var c=u.companies.find(function(x){return x.id===cid}); return c?{name:c.name,address:c.address,email:c.email,phone:c.phone,gstin:c.gstin}:{}}
function companyName(cid){return billTo(cid).name||''} function flat(o){var r={}; Object.keys(o).forEach(function(k){r[k]=typeof o[k]==='object'?JSON.stringify(o[k]):o[k]}); return r} function unflat(o){['items','descs','totals'].forEach(function(k){if(o[k])try{o[k]=JSON.parse(o[k])}catch(e){}}); return o} function log(u,text){u.activity=u.activity||[]; u.activity.push({text:text,at:new Date().toISOString()})} function toast(t){var el=document.createElement('div'); el.className='toast'; el.textContent=t; document.body.appendChild(el); setTimeout(function(){el.remove()},2400)}
window.Cos={edit:edit,del:del,editDoc:editDoc,preview:function(n,i){var u=me();previewDoc(n,u[n].find(function(x){return x.id===i}))},pdf:function(n,i){var u=me();downloadPdf(n,u[n].find(function(x){return x.id===i}))},moveLead:function(i){var u=me(),l=u.leads.find(function(x){return x.id===i}),st=['New','Qualified','Proposal','Won']; if(l)l.stage=st[(st.indexOf(l.stage)+1)%st.length]; store(u); renderAll()},deleteLead:function(i){var u=me(); u.leads=u.leads.filter(function(x){return x.id!==i}); store(u); renderAll()}};
init();
})();